require('user.plugins')
require('user.vimtex')
require('user.ultisnips')
require('user.colorscheme')
require('user.nvim-tree')
require('user.options')
require('user.keymaps')
require('user.telescope')