require ('user.options')
require ('user.keymaps')
require ('user.colorscheme')
require ('user.cmp')
require ('user.telescope')
require ('user.treesitter')
require ('user.nvim-tree' )
require ('user.plugins')
require ('user.vimtex')
